# =========================
# תצורת מערכת SpikeEngine (נרות 1m, פתיחה לפי הפרשי מחירים)
# =========================

spike:
  symbols:
    - SOL_USDT
    - BTC_USDT
  interval: "Min5"             # סוג הנר לבדיקה (1 דקה)
  cooldown_seconds: 5         # המתנה מינימלית בין עסקאות על אותו מטבע

  # סף פערי מחיר מותאם לכל מטבע
  thresholds:
    BTC_USDT: 150      # BTC → Spike אם ההפרש >= 300$
    SOL_USDT: 0.5      # SOL → Spike אם ההפרש >= 0.8$

telegram:
  enabled: true
  bot_token: "8172167806:AAHGr1UgKw6VYzXiYFkt-RwabqjMbX8KrBk"
  chat_id:
    - "5817603930"

risk:
  takeProfitPct: 300        # רווח באחוזים (TP קבוע מתוך config)
  percentPerTrade: 1      # אחוז מההון לפתיחת עסקה (לכל המטבעות)
  slTolerancePct: 0.0001   # טולרנס ל־SL דינמי (0.1%)

mexc_trades:
  SOL_USDT:
    symbol: "SOL_USDT"
    openType: 2
    type: 5
    leverage: 300
    priceProtect: 0

  BTC_USDT:
    symbol: "BTC_USDT"
    openType: 2
    type: 5
    leverage: 400
    priceProtect: 0
